### ISSUE TITLE
Corona Übersicht DE NL WO

### ISSUE THREAD

**Issue by martienl** [RudolfJagdhuber/corona_dashboard#2]
Hallo Herr Jagdhuber,

mit und durch Ihre Anwendung habe ich mich ein wenig in R eingearbeitet.
Eine interessante Geschichte, weil ich Ordnung in den Daten aus NL bringen wollte.
Das hat dann auch funktioniert, bis es vor ein paar Wochen sowohl bei den DE- als auch bei den
NL-Daten Probleme gab.

Wahrscheinlich haben auch Sie festgestellt, dass Ihre Version nicht mehr läuft.
Die Ursache hierfür ist eine Änderung des Datum-Formats und weil es eine Menge Daten
mit negativen Fallzahlen gab.
Letztere habe ich auf die schnelle schlichtweg positiv gemacht. Zwar falsch, aber immerhin
läuft das Ganze wieder.

Wenn Sie sich das anschauen möchten kann ich Ihnen die betreffenden Dateien gerne zukommen lassen.
Wenn mein Server läuft (normal tagsüber)  können Sie das Ergebnis ansehen unter 
https://ml.innovate.de/shiny/corona_dashboard/

Herzliche Grüße,

Martien Lammers 
div at innovate.de

**Comment by RudolfJagdhuber** [comment]
Hallo Herr Lammers,

Vielen Dank für die Nachricht. Freut mich dass ich Ihnen bei der Entwicklung Ihres Dashboards eine Vorlage geben konnte. Habe es mir gerade angesehen, sieht sehr gut aus und läuft.

Tatsächlich ist mir auch bereits aufgefallen, dass meine aktuelle Version nicht mehr funktioniert. Ich hatte bislang noch keine Zeit das Problem zu untersuchen und freue mich deshalb sehr, dass Sie es bereits gelöst haben.

Wenn Sie mir netterweise die betroffenen Dateien schicken würden, könnte ich es wahrscheinlich auch bei mir schnell beheben.

Vielen Dank dafür und Beste Grüße,
Dr. Rudolf Jagdhuber

**Comment by martienl** [comment]
Gerne!
Ich hoffe, im Anhang finden Sie alle Dateien.
Falls etwas fehlt, geben Sie Bescheid.

Herzliche Grüße,

Martien lammers

Am Samstag, 26. März 2022, 17:43:25 CET schrieb Dr. Rudolf Jagdhuber:
> Hallo Herr Lammers,
> 
> Vielen Dank für die Nachricht. Freut mich dass ich Ihnen bei der Entwicklung Ihres Dashboards eine Vorlage geben konnte. Habe es mir gerade angesehen, sieht sehr gut aus und läuft.
> 
> Tatsächlich ist mir auch bereits aufgefallen, dass meine aktuelle Version nicht mehr funktioniert. Ich hatte bislang noch keine Zeit das Problem zu untersuchen und freue mich deshalb sehr, dass Sie es bereits gelöst haben.
> 
> Wenn Sie mir netterweise die betroffenen Dateien schicken würden, könnte ich es wahrscheinlich auch bei mir schnell beheben.
> 
> Vielen Dank dafür und Beste Grüße,
> Dr. Rudolf Jagdhuber 
> 
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/RudolfJagdhuber/corona_dashboard/issues/2#issuecomment-1079730086
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
> 


-- 
Mit freundlichen Grüßen,

Martien Lammers

**Comment by RudolfJagdhuber** [comment]
Leider ist kein Anhang angekommen. Wahrscheinlich geht das über GitHub Issues mit dateien nicht.

**Comment by RudolfJagdhuber** [comment]
Jetzt hat es geklappt! Vielen Dank, habe das Repo nun auch schon aktualisiert. Jetzt läuft alles wieder. :-)
